### ISSUE TITLE
The bluetooth failed during operation

### ISSUE THREAD

**Issue by fengyanWang** [Alvipe/Open-Myo#3]
Hello, when I use your library to extract the original emg signal, the following question always appears. I don't know why. Hope to reply! thank you！

**> raise BTLEException(BTLEException.DISCONNECTED, "Device disconnected")
> bluepy.btle.BTLEException: Device disconnected**

**Comment by Alvipe** [comment]
Hi @fengyanWang, are you using the Bluetooth dongle included with the Myo Armband or a generic BTLE antenna (such as [this one](https://www.amazon.com/Wireless-Bluetooth-Dongle-Adapter-Windows/dp/B01ITDZ2A2))? This code only works with generic antennas; the dongle included with the Myo uses a proprietary protocol built upon the standard BTLE protocol.

**Comment by fengyanWang** [comment]
@Alvipe Thank you for your reply, I use is raspberry pie 3 b + on own bluetooth to directly communicate and myo, after multiple tests, find that as long as you keep the arm posture change range is not big, the equipment in the 30 s will probably into dormancy, and then disconnect bluetooth, my model has been set up never sleep mode, don't know the reason?

**Comment by Alvipe** [comment]
I am aware of this problem but I'm afraid that I still don't know what can be done to solve it. The command to put the Myo in "no sleep" mode is taken from the [Myo Bluetooth protocol](https://github.com/thalmiclabs/myo-bluetooth), just like the rest of the Open Myo code. It's weird because this is the only feature taken from the official protocol that doesn't work, so I don't know if its a problem of the Myo internal firmware or if it's a problem of my code.

Right now the trick is to shake the arm from time to time to prevent the device from falling asleep, which I know is not the best solution. I hope I can fix it at some point.

**Comment by Alvipe** [comment]
Hi @fengyanWang, I've merged the fix made by @qtux and it should work now without going to sleep and disconnecting. Please update your code with this fix and tell me if it works correctly now.

**Comment by Alvipe** [comment]
I finally have tested the fix made by @qtux and it works flawlessly, which means that this issue can be closed.
